routers:
  hosts:
      10.120.0.149:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_network_os: vyos
    ansible_connection: network_cli
    ansible_user: vyos
    ansible_ssh_pass: password
    ansible_persistent_command_timeout: 300
    ansible_command_timeout: 300
    