dhcp_server:
  networks:
    - name: NET_NSW01_ADMIN
      option:
        domain-name: "admin.sigaint.au"
        name-server: "10.120.10.1"
      subnets:
        - name: 10.120.10.0/24
          subnet-id: 1
          option:
            default-router: "10.120.10.1"
          static-mappings:
            - { name: idrac-6BFVY42,     ip-address: 10.120.10.10, mac: 74:e6:e2:fa:70:06 }
            - { name: idrac-8505qm2,     ip-address: 10.120.10.11, mac: 58:8a:5a:e7:4a:c2 }
            - { name: idrac-9qk2vg2,     ip-address: 10.120.10.12, mac: 84:7b:eb:d9:0d:c2 }
            - { name: idrac-9qd4vg2,     ip-address: 10.120.10.13, mac: 84:7b:eb:d9:0d:bc }
            - { name: xcc-7x02-j300cw5m, ip-address: 10.120.10.14, mac: 58:8a:5a:e7:4a:c2 }
            - { name: xcc-7x02-j300cw5k, ip-address: 10.120.10.15, mac: 58:8a:5a:e7:4a:c2 }
          range:
            0:
              start: 10.120.10.10
              stop: 10.120.10.100

    - name: NET_NSW01_SECURITY
      option:
        domain-name: "security.sigaint.au"
        name-server: "10.120.12.1"
      subnets:
        - name: 10.120.12.0/24
          subnet-id: 2
          option:
            default-router: "10.120.12.1"
          range:
            0:
              start: 10.120.12.10
              stop: 10.120.12.100

    - name: NET_NSW01_DMZ
      option:
        domain-name: "dmz.sigaint.au"
        name-server: "10.120.20.1"
      static-mappings: []
        #- { name: lan-gws-01, ip-address: 10.120.1.15, mac: ae:9d:22:e3:aa:f6 }
      subnets:
        - name: 10.120.20.0/24
          subnet-id: 3
          option:
            default-router: "10.120.20.1"
          range:
            0:
              start: 10.120.20.10
              stop: 10.120.20.100

    - name: NET_NSW01_HOSTING
      option:
        domain-name: "hosting.sigaint.au"
        name-server: "10.120.14.1"
      static-mappings:
        - { name: lan-node-01 , ip-address: 10.120.14.11, mac: 44:a8:42:0a:5e:e7 }
        - { name: lan-node-02 , ip-address: 10.120.14.12, mac: 80:18:44:ec:23:e6 }
        - { name: lan-node-03 , ip-address: 10.120.14.13, mac: 18:66:da:ef:6d:8a }
        - { name: lan-node-04 , ip-address: 10.120.14.14, mac: 18:66:da:ef:7d:aa }
        - { name: lan-node-05 , ip-address: 10.120.14.15, mac: 7c:d3:0a:59:3f:90 }
        - { name: lan-node-06 , ip-address: 10.120.14.16, mac: 38:68:dd:05:7e:d8 }
      subnets:
        - name: 10.120.14.0/24
          subnet-id: 4
          option:
            default-router: "10.120.14.1"
          range:
            0:
              start: 10.120.14.100
              stop: 10.120.14.200