dhcp_server:
  networks:
    - name: NET_NSW01_ADMIN
      option:
        domain-name: "sigaint.au"
        name-server: "10.120.0.33"
      subnets:
        - name: 10.120.0.32/27
          subnet-id: 1
          option:
            default-router: "10.120.0.33"
          static-mappings:
            - { name: idrac-6BFVY42,     ip-address: 10.120.0.46, mac: 74:e6:e2:fa:70:06 }
            - { name: idrac-8505qm2,     ip-address: 10.120.0.47, mac: 58:8a:5a:e7:4a:c2 }
            - { name: idrac-9qk2vg2,     ip-address: 10.120.0.48, mac: 84:7b:eb:d9:0d:c2 }
            - { name: idrac-9qd4vg2,     ip-address: 10.120.0.49, mac: 84:7b:eb:d9:0d:bc }
            - { name: xcc-7x02-j300cw5m, ip-address: 10.120.0.50, mac: 58:8a:5a:e7:4a:c2 }
            - { name: xcc-7x02-j300cw5k, ip-address: 10.120.0.51, mac: 58:8a:5a:e7:4a:c2 }
          range:
            0:
              start: 10.120.0.34
              stop: 10.120.0.62

    - name: NET_NSW01_CAMERA
      option:
        domain-name: "sigaint.au"
        name-server: "10.120.0.97"
      subnets:
        - name: 10.120.0.96/27
          subnet-id: 2
          option:
            default-router: "10.120.0.97"
          range:
            0:
              start: 10.120.0.100
              stop: 10.120.0.126

    - name: NET_NSW01_DMZ
      option:
        domain-name: "dmz.sigaint.au"
        name-server: "10.120.1.1"
      static-mappings:
        - { name: lan-gws-01, ip-address: 10.120.1.15, mac: ae:9d:22:e3:aa:f6 }
        - { name: lan-lb-01,  ip-address: 10.120.1.11, mac: da:33:c6:fe:b9:cc }
        - { name: lan-lb-02,  ip-address: 10.120.1.12, mac: ca:c6:92:97:8f:2b }
      subnets:
        - name: 10.120.1.0/24
          subnet-id: 3
          option:
            default-router: "10.120.1.1"
          range:
            0:
              start: 10.120.1.10
              stop: 10.120.1.100

    - name: NET_NSW01_HOSTING
      option:
        domain-name: "hosting.sigaint.au"
        name-server: "10.120.0.225"
      static-mappings:
        - { name: lan-node-01 , ip-address: 10.120.0.230, mac:  }
        - { name: lan-node-02 , ip-address: 10.120.0.231, mac:  }
        - { name: lan-node-03 , ip-address: 10.120.0.232, mac:  }
        - { name: lan-node-04 , ip-address: 10.120.0.233, mac:  }
        - { name: rancher,      ip-address: 10.120.0.229, mac:  }
      subnets:
        - name: 10.120.0.224/27
          subnet-id: 4
          option:
            default-router: "10.120.0.225"
          range:
            0:
              start: 10.120.0.230
              stop: 10.120.0.225