firewall_zones:
  # The name `LOCAL` is reserved for the local zone
  - name: "LOCAL"
    description: "Local zone"
    local_zone: true
    firewalls:
      from:
         - { zone: "WAN", name: "WAN-LOCAL",   protocol: ipv4 } # ipv6: true if ipv6
         - { zone: "WAN", name: "WAN-LOCAL-6", protocol: ipv6 } # ipv6: true if ipv6

  - name: "WAN"
    description: "The Internet"
    default_action: accept
    interface: "eth0"
    firewalls:
      from:
        - { zone: "WIFI",  name: "WIFI-WAN",    protocol: ipv4 } # ipv6: true if ipv6
        - { zone: "LOCAL", name: "LOCAL-WAN",   protocol: ipv4 } # ipv6: true if ipv6
        - { zone: "LOCAL", name: "LOCAL-WAN-6", protocol: ipv6 } # ipv6: true if ipv6

  - name: "ADMIN"
    description: "Admin Zone"
    interface: "br0.10"
    firewalls:
      from:
        - { zone: "PROTECTED", name: "ADMIN-PROTECTED", protocol: ipv4 } # ipv6: true if ipv6

  - name: "PROTECTED"
    description: "Administration environment"
    interface: "br0.11"
    firewalls:
      from:
        - { zone: "ADMIN", name: "PROTECTED-ADMIN", protocol: ipv4 } # ipv6: true if ipv6

  - name: "SECURITY"
    description: "Security Administration"
    interface: "br0.12"
    firewalls:
      from:
        - { zone: "WIFI", name: "WIFI-SECURITY", protocol: ipv4 } # ipv6: true if ipv6

  - name: "WIFI"
    description: "WIFI zone"
    interface: "br0.13"
    firewalls:
      from:
        - { zone: "WAN", name: "WAN-WIFI", protocol: ipv4 } # ipv6: true if ipv6

  - name: "DMZ"
    description: "Internet connected"
    interface: "br0.20"
    firewalls:
      from: []

  - name: "DMZ"
    description: "Internet connected"
  - name: "VMNET"
    description: "Internal hosting"
    interface: "br0.21"
    firewalls:
      from: []

firewalls:

  ##########################################################
  # IPv4 Firewall Rules go here                            #
  ##########################################################

  - name: WAN-WIFI
    protocol: ipv4
    description: Internet to WiFi IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 110
        rule: |
          action reject
          state invalid
      
  - name: WIFI-WAN
    protocol: ipv4
    description: WiFi to Internet IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          description "Accept All Traffic"
          action accept

  - name: WIFI-SECURITY
    protocol: ipv4
    description: WiFi to Security IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 110
        rule: |
          action reject
          state invalid
      - number: 120
        rule: |
          action accept
          description "Blue Iris"
          destination {
              address 10.120.12.10
              port 443,80,81,3389
          }
          protocol tcp

  - name: PROTECTED-ADMIN
    protocol: ipv4
    description: Protected to Admin IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 110
        rule: |
          action reject
          state invalid
      - number: 120
        rule: |
          action accept
          description "Device management access OOB"
          destination {
            group {
              address-group OUT_OF_BAND
            }
          }
          protocol tcp_udp
      - number: 130
        rule: |
          action accept
          description "Device management access OTHER"
          destination {
            group {
              address-group MANAGEMENT
            }
          }
          protocol tcp_udp

  - name: ADMIN-PROTECTED
    protocol: ipv4
    description: Admin to Protected network IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 110
        rule: |
          action reject
          state invalid

  - name: LOCAL-WAN
    protocol: ipv4
    description: LOCAL to WAN IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept

  - name: LOCAL-WAN-6
    protocol: ipv6
    description: LOCAL to WAN IPv6
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept

  - name: WAN-LOCAL
    protocol: ipv4
    description: WAN to LOCAL IPv4
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 110
        rule: |
          action accept
          destination {
              port 22
          }
          protocol tcp

##########################################################
# IPv6 Firewall Rules go here                            #
##########################################################
  - name: WAN-LOCAL-6
    protocol: ipv6
    description: Internet to Local IPv6
    default_action: reject
    rules:
      - number: 100
        rule: |
          action accept
          state established
          state related
      - number: 120
        rule: |
          action accept
          protocol icmpv6
      - number: 130
        rule: |
          action accept
          description "DHCPv6 Replies"
          destination {
              port 546
          }
          protocol udp
          source {
              port 547
          }
