firewall_groups:
  port_groups:

    # Place all the mandatory ports for IPA
    # into a port group to make the firewall rules
    # easier to manage.
    #
    - name: IPA_PORTS
      ports:
        - 80
        - 443
        - 389
        - 636
        - 88
        - 464
        - 123 # ntp, its easy as ...

  address_groups:

    # Out of band management addresses
    # for XClarity and iDRAC devices
    # as well as the APC
    #
    - name: OUT_OF_BAND
      addresses:
        - 10.120.10.10 # idrac-1
        - 10.120.10.11 # idrac-2
        - 10.120.10.12 # idrac-3
        - 10.120.10.13 # idrac-4
        - 10.120.10.14 # idrac-5

    # NTP servers for time sync
    # We use the Google ones here switching from ANU.
    #
    - name: NTP_SERVERS
      addresses:
        - 216.239.35.0 # time1.google.com
        - 216.239.35.4 # time2.google.com
        - 216.239.35.8 # time3.google.com

    # Quad 9 DNS servers (ipv4)
    - name: DNS_SERVERS
      addresses:
        - 9.9.9.9
        - 149.112.112.112