interfaces:
  ethernet:
    - name: eth0
      description: "NET_NSW01_WAN"
      address:
        - dhcp
        - dhcpv6
      ipv6:
        enable: true
        address:
          - autoconf
      dhcpv6-options:
        pd:
          0:
            length: 56
            interfaces:
              - name: "br0.13"
                address: 1
                sla-id: 0
              - name: "br0.20"
                address: 1
                sla-id: 1
  bridges:
    - name: br0
      members:
        - interface: eth3
          allowed_vlan: "10-50"
        - interface: eth4
          allowed_vlan: "10-50"
      vifs:
        - vlan_id: 10
          address:
            - 10.120.10.1/24
          description: "NET_NSW01_ADMIN"
        - vlan_id: 11
          address:
            - 10.120.11.1/27
          description: "NET_NSW01_PROTECTED"
        - vlan_id: 12
          address:
            - 10.120.12.1/24
          description: "NET_NSW01_SECURITY"
        - vlan_id: 13
          address:
            - 10.120.13.1/24
          description: "NET_NSW01_WIFI"
        - vlan_id: 14
          address:
            - 10.120.14.1/24
          description: "NET_NSW01_HOSTING"
        - vlan_id: 20
          address:
            - 10.120.20.1/24
          description: "NET_NSW01_DMZ"
        - vlan_id: 21
          address:
            - 10.120.21.1/24
          description: "NET_NSW01_VMNET"