- hosts: routers
  gather_facts: 'no'
  tasks:
    - debug:
        msg: "{{ lookup('template', '../templates/dhcp-server.j2') }}"

    - name: sigaint-vyos | configure dhcp-server
      vyos.vyos.vyos_config:
        src: "../templates/dhcp-server.j2"
